# Generated by Django 5.0 on 2023-12-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_color_product_remove_size_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descrip',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
