# Generated by Django 5.0 on 2023-12-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descrip',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
