# Generated by Django 5.0 on 2023-12-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_carditem_color_carditem_size_oderitem_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oderitem',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oderitem',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
