# Generated by Django 5.0 on 2023-12-14 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_carditem_color_alter_carditem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.color'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.size'),
        ),
        migrations.AlterField(
            model_name='oderitem',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.color'),
        ),
        migrations.AlterField(
            model_name='oderitem',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.size'),
        ),
    ]
