# Generated by Django 5.0 on 2023-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_carditem_color_alter_carditem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='status',
            field=models.CharField(choices=[('Bought', 'Bought'), ('Ordered', 'Ordered'), ('Ordering', 'Ordering'), ('Incart', 'Incart')], default='Incart', max_length=15),
        ),
    ]
